/** Built-in silly family-friendly prompts for Picture Telephone */
export const PROMPTS = [
  "A cat wearing sunglasses at the beach",
  "A dinosaur riding a bicycle",
  "A robot baking cookies",
  "An octopus playing the piano",
  "A penguin in a superhero cape",
  "A squirrel delivering pizza",
  "A dragon brushing its teeth",
  "A frog with a tiny umbrella",
  "A unicorn stuck in traffic",
  "A bear reading a bedtime story",
  "A flamingo doing yoga",
  "A raccoon stealing popcorn",
  "A whale in a bathtub",
  "A chicken driving a taxi",
  "A ghost eating spaghetti",
  "A cactus wearing a cowboy hat",
  "A snail racing a cheetah",
  "A monkey juggling bananas",
  "A owl in pajamas",
  "A goat painting a masterpiece",
  "A shark wearing flip-flops",
  "A duck on a skateboard",
  "A koala sipping hot cocoa",
  "A lobster at a fancy dinner",
  "A giraffe peeking through a window",
  "A hamster lifting weights",
  "A turtle with jet packs",
  "A porcupine hugging a balloon",
  "A moose in roller skates",
  "A butterfly carrying a suitcase",
  "Two tacos having an argument",
  "A sandwich that learned to fly",
  "A potato running for mayor",
  "A sock looking for its twin",
  "A pizza slice surfing a wave",
  "A banana slipping on a peel",
  "A cookie escaping the jar",
  "A teapot pouring rainbows",
  "A broom sweeping up stars",
  "A clock that only ticks jokes",
  "Kids building a fort of pillows",
  "A family of clouds having a picnic",
  "A rainbow stuck in a traffic cone",
  "A snowman melting into a puddle dance",
  "A lightning bolt taking a nap",
  "A mountain wearing sunglasses",
  "A volcano blowing bubblegum bubbles",
  "The moon juggling planets",
  "A spaceship shaped like a shoe",
  "Aliens learning to high-five",
];

export function randomPrompt() {
  return PROMPTS[Math.floor(Math.random() * PROMPTS.length)];
}
